import Head from "next/head";
import React from "react";
import Header from "../header/Header";
import Footer from "../footer/Footer";
export const metadata = {
  title: "Caja la Araucana",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

export const MainLayout = ({ children }: Props) => {
  return (
    <React.Fragment>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.title} />
        <link rel="icon" href="/crom/mf-host/favicon.ico" />
      </Head>
      <div className="h-full flex flex-col justify-between items-center">
        <Header />
        <main className="py-5">{children}</main>
        <Footer />
      </div>
    </React.Fragment>
  );
};
